### ISSUE TITLE
观察模式

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#13]
@CarmJos @LyzenX

### **问题简述**

如果玩家在地图里打开过观察模式（右键末影珍珠），同一个服务器同一张地图的其他玩家无法看到该玩家

### **问题操作**

右键末影珍珠

### **预期结果**(可选)

玩家可以互相看到

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有):
- 地图名(如果有): 全服

**Comment by Maverical** [comment]
创意工坊地图中：
视频刚开始玩家用了4X_mf这个号
然后他切回另一个号（正在使用观察模式）
他关闭观察模式之后，玩家切回4X_mf这个号
发现无法看到使用过观察模式的那个号
（视频已QQ发）

**Comment by CarmJos** [comment]
可能暂时无法解决。

**Comment by Maverical** [comment]
什么理由呢

**Comment by CarmJos** [comment]
未知问题，暂时没法修



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月12日(周二) 晚上10:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PurpleMonkey-Games/ServerIssues] 观察模式 (Issue #13)




 
什么理由呢
