### ISSUE TITLE
创意工坊特殊方块添加

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#14]
@CarmJos @LyzenX

### **功能简述**

添加刷怪笼方块

### **需求来源**

玩家反映

**Comment by LyzenX** [comment]
可以使用“创意物品包”
`/pa ItemPack`
以自行添加任何特殊物品到某类别中
需注意的是，对于头颅，不能使用指定头颅名的方式(如"CUMR")，而应采用texture的方式(如"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTY3ZDgxM2FlN2ZmZTViZTk1MWE0ZjQxZjJhYTYxOWE1ZTM4OTRlODVlYTVkNDk4NmY4NDk0OWM2M2Q3NjcyZSJ9fX0=")
创意物品包将会在下一次更新中实装
