### ISSUE TITLE
创意工坊打赏功能：在创意地图列表中无法显示新的水晶打赏

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#23]
@CarmJos 

### **问题简述**

新的水晶打赏作者能收到水晶，但是无法显示在创意中，其他玩家看不到更新

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有): meihua/4X_mf
- 地图名(如果有): 创意工坊“万圣螺旋塔”

**Comment by Maverical** [comment]
![2023-12-09_20 03 59](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/1e694fca-bf75-403f-a660-e0487a86f15c)
我给这张图打了200水晶，显示为0

**Comment by LyzenX** [comment]
可能是因为储存数据至数据库时出现了错误，已修复，待验证
