### ISSUE TITLE
邮差右键无反应

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#31]
@CarmJos 

### **问题简述**

邮差点了没反应

### **问题截图/问题报错**

![2023-12-04_21 35 21](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/e042450c-0996-40c8-ab1c-6ac561fd5257)

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有):
- 地图名(如果有):

**Comment by LyzenX** [comment]
邮件系统还没有GUI，固目前邮差NPC还没有实际作用
