### ISSUE TITLE
创意工坊功能方块设置触发方式为踩下（单发）后，玩家无法“跳上“方块去触发

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#32]
@CarmJos 

### **问题简述**

创意工坊功能方块设置触发方式为踩下（单发）后玩家无法跳上方块去触发，走上去也是有概率触发，之前没有这个问题，之前可以跳上方块触发

### **预期结果**(可选)

应该是玩家跳跃/步行接触到功能方块后都能正常触发功能方块

### **问题截图/问题报错**

有视频

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有):
- 地图名(如果有): 所有创意工坊地图

**Comment by LyzenX** [comment]
修改了判定方式，待进一步测试

**Comment by LyzenX** [comment]
有时候玩家跳到方块的边缘，导致判定的是旁边的方块，对于这种单方块的情况，可使用*"范围识别功能方块"*，多框选住该方块旁边的方块(即便是空气，先用其他方块占位便于设置范围起点和终点，再破坏掉占位方块)，这样对于“单发”的情况，走进范围只会触发一次，走出范围后再次走进可重新触发。
要注意的是，如果只设置了单层高的范围，玩家在该方块上跳起再落下可再触发，如果不希望这样，可将范围高度设置成两层高，这样就可以避免因起跳而跳出范围。
*该判定方式在下一次维护时更新至全服
