### ISSUE TITLE
创意工坊玩家Issactar他的创意世界内不能聊天

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#33]
@CarmJos 

### **问题简述**

创意工坊玩家创意世界内不能聊天

### **操作环境**
- 服务器类型:
- 客户端版本: 1.18.2

- 反馈人IGN(如果有): Issactar
- 地图名(如果有): 砖块跑酷

**Comment by CarmJos** [comment]
请检查自己的客户端问题。

**Comment by Maverical** [comment]
有办法查到昨天晚上的异常记录吗？我昨天直播的时候出的问题，当时我和其他玩家都没办法在这个世界里发消息，现在已经好了

**Comment by Maverical** [comment]
问题第二次出现，出问题的地图是玩家GLqMCpk的跑酷天堂，在地图中的所有玩家都不能发送聊天消息，视频记录：
https://www.bilibili.com/video/BV1C64y1V72D/?spm_id_from=333.999.0.0&vd_source=909f3153e1d0423f3ca9f72bea9e44ab

**Comment by CarmJos** [comment]
暂时无法处理。
