### ISSUE TITLE
创意工坊点赞功能：在创意工坊中给上架的地图的点赞不会显示

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#34]
@CarmJos 
### **问题简述**

给创意工坊的地图的点赞不显示

### **问题截图/问题报错**

![2023-12-17_14 13 10](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/a3aefeed-d96e-4a9a-bc95-404173103e0d)

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有):
- 地图名(如果有): 山涧之旅等所有创意工坊地图

**Comment by Maverical** [comment]
补充证据
![QQ图片20240114163638](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/7ac56be4-2519-4e90-af7e-e3d2fcf3acf1)
![QQ图片20240114163659](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/ac5e55ac-df44-4bdd-99b2-eb54af0ba219)

**Comment by LyzenX** [comment]
上架到创意市场上的是正确的数据，而自己背包中的是缓存数据，缓存数据是不准确的，应自动校准但实际没有校准，现已修复自动校准，问题修复。
