### ISSUE TITLE
灵魂PK功能BUG：玩家无法看到灵魂且玩家和灵魂之间有碰撞体积

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#36]
@CarmJos @LyzenX

### **问题简述**

灵魂PK功能BUG：玩家无法看到灵魂且玩家和灵魂之间有碰撞体积

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有):
- 地图名(如果有):

**Comment by CarmJos** [comment]
检查到是在获取玩家皮肤时出现网络问题导致无法正常显示。
