### ISSUE TITLE
创意工坊已上架跑酷地图内排行榜显示问题（有视频太大无法上传）

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#37]
@CarmJos @LyzenX

### **问题简述**

创意工坊已上架跑酷地图内排行榜会有盔甲架一直旋转，屏幕闪烁等问题

### **问题截图/问题报错**

![@2_6NZRC@8N 4FAPKRFGAQN](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/bbaf0cd7-625c-43bb-828f-f808c01ec95f)

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有): GLqMCpk
- 地图名(如果有): Dimension Paradise

### **其他补充**

视频中的玩家有安装mod或其他插件，可从视频推出

![DSJV50_CN(0``N(%F4Z5}LC](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/99e78489-168d-4972-928e-fc1d11018634)

**Comment by CarmJos** [comment]
Hologram实现的原理就是防止隐身的盔甲架。目测应该是客户端的模组吧盔甲架显示出来了，非服务器问题，无法复现。
