### ISSUE TITLE
feat(brush): 创意工坊笔刷功能添加空气笔刷

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#39]
@CarmJos @LyzenX

### **功能简述**

创意工坊笔刷功能添加空气笔刷，之前好像和我说过无法实现该功能，我看我还没有提交过issue，想再试试

### **需求来源**

建造复杂地形，地形建筑师的必需品

**Comment by CarmJos** [comment]
空气笔刷是个什么东西？
