### ISSUE TITLE
fix(creative): 修复创意工坊生存模式带来的问题

### ISSUE THREAD

**Issue by CarmJos** [PurpleMonkey-Games/ServerIssues#40]
- [x] 每一个水桶/岩浆桶/细雪桶只能使用一次，应当只给予一件并放置时重置。
- [x] 获取非堆叠物品时，应当只给予1件。
  - 如 将桶类物品悬于物品栏之上不放下，退出背包后会导致自动填满背包。
- [ ] 左右键无法同时按下来替换单格方块。 有无好的解决方案？
- [x] 破坏方块没有音效和粒子。
- [x] 没有调试棒物品，且调试棒无法使用。

**Comment by LyzenX** [comment]
- `获取非堆叠物品时，应当只给予1件`: 确实是给`item.getMaxStackSize()`件，但不知为何只有部分物品有效，对于另一些物品(如装备等)则给了64件(EDIT: 确实是代码中一处写错了，已修复)
- `没有调试棒物品，且调试棒无法使用`: 可在*创意工坊菜单-特殊方块*中获取调试棒，如需在*物品列表*中添加，可在大厅使用指令`/pa itempack`进行添加。非op玩家生存模式下使用调试棒，需有权限`minecraft.debugstick`和`minecraft.debugstick.always`
- `破坏方块没有音效和粒子`: 生存模式破坏方块是通过`p.breakBlock(block)`实现的，貌似它不会有音效和粒子

**Comment by LyzenX** [comment]
左右键无法同时按下来替换单格方块: 识别左键一个方块后短时间内触发右键空气的事件，则把手上的方块敀至目标位置

**Comment by LyzenX** [comment]
`左右键无法同时按下来替换单格方块`    目前无法解决
