### ISSUE TITLE
跑酷手持物品交互

### ISSUE THREAD

**Issue by Maverical** [PurpleMonkey-Games/ServerIssues#7]
@CarmJos @LyzenX

### **问题简述**

在练习服，当玩家站在记录点上时无法使用除了观察之外的功能，右键/shift右键都没有反应

### **问题操作**

如果玩家站在记录点上，右键床，shift右键铁门，右键末影之眼，右键羽毛，右键黄绿色染料都没有反应

### **预期结果**(可选)

以上操作均可实现

### **问题截图/问题报错**

![跑酷手持物品交互1](https://github.com/PurpleMonkey-Games/ServerIssues/assets/108687159/c67eb01c-2441-4311-9b06-77df159496c6)

### **操作环境**
- 服务器类型:
- 客户端版本:

- 反馈人IGN(如果有): 7s_Half
- 地图名(如果有):

**Comment by Maverical** [comment]
请问这个问题有什么进展吗？

**Comment by CarmJos** [comment]
该问题应该暂时没有办法解决。

**Comment by Maverical** [comment]
请问为什么暂时没有办法解决？
BUG更新：不仅是记录点上，只要是在压力板上就没办法互动

**Comment by CarmJos** [comment]
就是因为找不到为什么，所以暂时无法解决。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月12日(周二) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PurpleMonkey-Games/ServerIssues] 跑酷手持物品交互 (Issue #7)




 
请问为什么暂时没有办法解决？
 BUG更新：不仅是记录点上，只要是在压力板上就没办法互动

**Comment by LyzenX** [comment]
已修复
